// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/types/database';

const SUPABASE_URL = "https://qdbvxznnzukdwooziqmd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFkYnZ4em5uenVrZHdvb3ppcW1kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkwNjQ3MTIsImV4cCI6MjA4NDY0MDcxMn0.Wx9whOkBYmMdGzj1u3VKZyXtcr77H-rM3i4PViASf4c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});